name: lipl_app_bloc
description: Library request and handle response from Lipl Service
publish_to: none
version: 1.2.2

environment:
  sdk: ^3.2.0

dependencies:
  bloc: ^8.1.1
  dio: ^5.1.1
  freezed_annotation: ^2.4.1
  lipl_model:
    path: "../lipl-model"
  loading_status:
    path: "../loading-status"
  logging: ^1.1.1
  retrofit: ^4.0.1

dev_dependencies:
  environment:
    path: "../environment"
  bloc_test: ^9.1.1
  build_runner: ^2.4.6
  build_test: ^2.1.7
  http_mock_adapter: ^0.6.0
  retrofit_generator: ^8.0.4
  flutter_lints: ^3.0.1
  mocktail: ^1.0.1
  path: ^1.8.3
  test: ^1.24.2
  uuid: ^4.2.1
  fast_base58: ^0.2.1
  freezed: ^2.4.5

