name: lipl_app_bloc
description: Library request and handle response from Lipl Service
repository: https://github.com/paulusminus/lipl-control/
publish_to: none
version: 1.13.13

environment:
  sdk: ^3.7.2
resolution: workspace

dependencies:
  bloc: ^9.0.0
  dio: ^5.1.1
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^4.0.0
  flutter:
    sdk: flutter
  freezed_annotation: ^3.0.0
  hydrated_bloc: ^10.0.0
  json_annotation: ^4.9.0
  lipl_model: ^1.13.10
  logging: ^1.2.0
  retrofit: ^4.0.1

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.6
  build_test: ^2.1.7
  http_mock_adapter: ^0.6.0
  json_serializable: ^6.7.1
  retrofit_generator: ^9.0.0
  lints: ^5.0.0
  mocktail: ^1.0.1
  path: ^1.8.3
  test: ^1.24.2
  uuid: ^4.2.1
  fast_base58: ^0.2.1
  freezed: ^3.0.0
