name: lipl_control
description: App to maintain lyrics and playlists and send text to lipl-display
repository: https://github.com/paulusminus/lipl-control/
publish_to: 'none'
version: 1.9.3

environment:
  sdk: ^3.4.0
  flutter: ^3.22.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^8.1.4
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.5
  http: ^1.2.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  lipl_bluetooth:
    path: packages/lipl-bluetooth
  lipl_model:
    path: packages/lipl-model
  lipl_app_bloc: 
    path: packages/lipl-app-bloc
  loading_status:
    path: packages/loading-status
  logging: ^1.2.0
  universal_io: ^2.2.2
  flutter_gen: ^5.5.0
  path_provider: ^2.1.3
  hydrated_bloc: ^9.1.5
  freezed_annotation: ^2.4.1
dev_dependencies:
  build_runner: ^2.4.10
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  bloc_test: ^9.1.7
  flutter_lints: ^4.0.0
  freezed: ^2.5.2

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: false
  image_path: 'assets/icon/icon.png'
  remove_alpha_ios: true
  adaptive_icon_background: #ffffff
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: #0175C2
    theme_color: #0175C2
