name: loading_status
description: Loading Status enumeration
repository: https://github.com/paulusminus/lipl-control/
version: 1.0.5
publish_to: 'none'

environment:
  sdk: ^3.2.5

dev_dependencies:
  lints: ^3.0.0
