name: loading_status
description: Loading Status enumeration
repository: https://github.com/paulusminus/lipl-control/
version: 1.0.6
publish_to: 'none'

environment:
  sdk: ^3.4.0

dev_dependencies:
  lints: ^4.0.0
