name: lipl_control
description: App to maintain lyrics and playlists and send text to lipl-display
repository: https://github.com/paulusminus/lipl-control/
publish_to: "none"
version: 1.13.17

environment:
  sdk: ^3.9.2
resolution: workspace

dependencies:
  bloc: ^9.0.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_gen: ^5.5.0
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^3.0.0
  go_router: ^16.1.0
  hydrated_bloc: ^10.0.0
  http: ^1.2.1
  intl: ^0.20.0
  json_annotation: ^4.9.0
  lipl_app_bloc: ^1.13.12
  lipl_bluetooth: ^1.13.12
  lipl_model: ^1.13.12
  logging: ^1.2.0
  package_info_plus: ^9.0.0
  path_provider: ^2.1.3
  universal_io: ^2.2.2
dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.10
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.0
  integration_test:
    sdk: flutter
  json_serializable: ^6.8.0

flutter_launcher_icons:
  adaptive_icon_background: #ffffff
  android: "launcher_icon"
  image_path: "assets/icon/icon.png"
  ios: false
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: #0175C2
    theme_color: #0175C2

flutter:
  generate: true
  uses-material-design: true
