name: environment
description: Get environment variables needed for testing
repository: https://github.com/paulusminus/lipl-control/
version: 1.12.4

environment:
  sdk: ^3.4.1

dev_dependencies:
  lints: ^4.0.0
