name: environment
description: Get environment variables needed for testing
repository: https://github.com/paulusminus/lipl-control/
version: 1.0.3

environment:
  sdk: ^3.2.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
