name: environment
description: Get environment variables needed for testing
repository: https://github.com/paulusminus/lipl-control/
version: 1.0.2

environment:
  sdk: ^3.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
