name: environment
description: Get environment variables needed for testing
repository: https://github.com/paulusminus/lipl-control/
version: 1.0.6

environment:
  sdk: ">=3.3.0 <4.0.0"

dev_dependencies:
  lints: ^4.0.0
