name: lipl_encrypt
description: Encryption used when storing preferences
repository: https://github.com/paulusminus/lipl-control/
version: 1.2.10

environment:
  sdk: ^3.4.0

dependencies:
  encrypt: ^5.0.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.2
