name: lipl_encrypt
description: Encryption used when storing preferences
repository: https://github.com/paulusminus/lipl-control/
version: 1.2.2

environment:
  sdk: ^3.2.5

dependencies: 
  encrypt: ^5.0.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.2
