name: lipl_encrypt
description: A starting point for Dart libraries or applications.
version: 1.2.0

environment:
  sdk: ^3.1.5

dependencies: 
  encrypt: ^5.0.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.2
