name: lipl_encrypt
description: A starting point for Dart libraries or applications.
version: 1.2.1

environment:
  sdk: ^3.2.0

dependencies: 
  encrypt: ^5.0.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.2
