name: preferences_bloc
description: Library for handling preferences changes and storing
version: 1.2.0
publish_to: 'none'

environment:
  sdk: ^3.1.5

dependencies:
  bloc: ^8.1.1
  equatable: ^2.0.5
  loading_status:
    path: "../loading-status"

dev_dependencies:
  environment:
    path: "../environment"
  bloc_test: ^9.1.1
  lints: ^3.0.0
  test: ^1.24.9
