name: Flutter test and build web

on:
  push:
    branches: ["main"]

env:
  LIPL_USERNAME: ${{ secrets.LIPL_USERNAME }}
  LIPL_PASSWORD: ${{ secrets.LIPL_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - name: Test lipl-app-bloc
        run: flutter test -r expanded
        working-directory: "./packages/lipl-app-bloc"
      - name: Test lipl-model
        run: flutter test -r expanded
        working-directory: "./packages/lipl-model"
      - name: Test Lipl Control
        run: flutter test -r expanded
        working-directory: "./packages/app"
      - name: Build for Web
        run: flutter build web --release
        working-directory: "./packages/app"
      - name: Create tarball
        run: tar -czf ../../web.tar.gz .
        working-directory: "./packages/app/build/web"
