# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter

on:
  push:
    branches: [ "main", "flutter_blue_plus" ]

env:
  LIPL_USERNAME: ${{ secrets.LIPL_USERNAME }}
  LIPL_PASSWORD: ${{ secrets.LIPL_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.3'
      - name: Test lipl-app-bloc
        run: flutter test -r expanded
        working-directory: './packages/lipl-app-bloc'
      - name: Test lipl-model
        run: flutter test -r expanded
        working-directory: './packages/lipl-model'
      - name: Test preferences-bloc
        run: flutter test -r expanded
        working-directory: './packages/preferences-bloc'
      - name: Test lipl-encrypt
        run: flutter test -r expanded
        working-directory: './packages/lipl-encrypt'
      - name: Test 
        run: flutter test -r expanded
      - name: Build for Web
        run: flutter build web
