name: Release tarball

on:
  push:
    tags: "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: false
      - name: Build for Web
        run: flutter build web --release
      - name: Create pwa tarball
        working-directory: build/web/
        run: tar -czf ../../lipl-pwa.tar.gz --owner=0 --group=0 .
      - name: Build linux app
        run: flutter build linux
      - name: Create linux executable tarball
        working-directory: build/linux/x64/release/bundle
        run: tar -czf ../../../../../lipl-linux-x64.tar.gz --owner=0 --group=0 .
      - name: Calculate checksum
        run: sha256sum lipl-linux-x64.tar.gz > lipl-linux-x64.tar.gz.sig.txt
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "lipl-pwa.tar.gz,lipl-linux-x64.tar.gz,lipl-linux-x64.tar.gz.sig.txt"
