name: Release pwa tarball

on:
  push:
    tags: [ 'v*.*.*' ]


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - name: Build html
        run: flutter build web --base-href "/lipl/app/"
      - name: Tarball
        run: tar -czf ../../web.tar.gz --owner=0 --group=0 --no-same-owner --no-same-permissions .
        working-directory: build/web
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "web.tar.gz"
