name: Release tarball

on:
  push:
    tags: "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: false
      - name: Build for Web
        run: flutter build web --release
      - name: Create tarball
        working-directory: build/web/
        run: tar -czf ../../lipl-pwa.tar.gz --owner=0 --group=0 .
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "lipl-pwa.tar.gz"
